version: '2'
services:
  mysql_serv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
    #volumes:
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf
      #- /var/lib/mysql

  wordpress_serv:
    image: wordpress:4.7.2
    environment:
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_HOST: mysql_serv:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
      MYSQL_PASSWORD: testtest
    ports:
      - "8702:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql_serv
    links:
      - mysql_serv
