version: '2'
services:
  mysql_data:
    image: busybox
    volumes:
      - /var/lib/mysql

  mysql_serv:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
    volumes_from:
      - mysql_data

  wordpress_serv:
    build: Dockerfile.wordpress
    #image: my_wordpress:4.9.4
    environment:
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_HOST: mysql_serv:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
      MYSQL_PASSWORD: testtest
    ports:
      - "8888:80"
    volumes:
      #- ./html:/var/www/html
      - "$PWD/html:/var/www/html"
    depends_on:
      - mysql_serv
    links:
      - mysql_serv
