version: '2'
services:
  mysql_data:
    image: busybox
    volumes:
      - /var/lib/mysql

  mysql_serv:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: testtest
    volumes_from:
      - mysql_data

  wordpress_serv:
    build: Dockerfile.wordpress
    environment:
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_HOST: mysql_serv:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DEBUG: 1
      MYSQL_PASSWORD: testtest
      # for docker nginx
      # - VIRTUAL_HOST=hoge.example.com
      # - LETSENCRYPT_HOST=hoge.example.com
      # - LETSENCRYPT_EMAIL=infodesk@feem.co.jp
    ports:
      - "${DOCKER_MAP_PORT}:80"
    volumes:
      # - ./html:/var/www/html
      - ./wordpress/wp-content/languages:/var/www/html/wp-content/languages
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql_serv
    links:
      - mysql_serv

# networks:
#   default: